/**
 * @enum ROUTE_NAME
 */
export enum ROUTE_NAME {
  CONFIG = 'CONFIG',
  COMMENT_LIST = 'COMMENT.LIST',
  DISH_LIST = 'DISH.LIST',
  EVENT_LIST = 'EVENT.LIST',
  LOGIN = 'AUTH.LOGIN',
  MAIN = 'MAIN',
}
