/**
 * @enum ROUTE_NAME
 */
export enum ROUTE_NAME {
    CONFIG = 'APP.CONFIG',
    DESTINATIONS = 'APP.DESTINATIONS',
    LOGIN = 'AUTH.LOGIN',
    MAIN = 'MAIN',
    PRODUCTS = 'PRODUCTS',
    PRODUCT_EDIT = 'PRODUCT_EDIT',
    USERS = 'USERS',
}